from datetime import date
import holidays


#custome made holidays

custom_holidays = holidays.HolidayBase()
year=2020
custom_holidays.append({"{0}-{1}-{2}".format(year,1,1): "New Year's Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,1,2): "Guru Govind Singh Jayanti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,1,14): "Lohri"})
custom_holidays.append({"{0}-{1}-{2}".format(year,1,15): "Pongal"})
custom_holidays.append({"{0}-{1}-{2}".format(year,1,15): "Makar Sankranti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,1,25): "Chinese New Year"})
custom_holidays.append({"{0}-{1}-{2}".format(year,1,26): "Republic Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,1,30): "Vasant Panchami"})
custom_holidays.append({"{0}-{1}-{2}".format(year,2,9): "Guru Ravidas Jayanti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,2,14): "Valentine's Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,2,18): "Maharishi Dayanand Saraswati Jayanti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,2,19): "Shivaji Jayanti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,2,21): "Maha Shivaratri/Shivaratri"})
custom_holidays.append({"{0}-{1}-{2}".format(year,3,9): "Holika Dahana"})
custom_holidays.append({"{0}-{1}-{2}".format(year,3,9): "Hazarat Ali's Birthday"})
custom_holidays.append({"{0}-{1}-{2}".format(year,3,10): "Holi"})
custom_holidays.append({"{0}-{1}-{2}".format(year,3,20):"March Equinox"})
custom_holidays.append({"{0}-{1}-{2}".format(year,3,25): "Chaitra Sukhladi"})
custom_holidays.append({"{0}-{1}-{2}".format(year,4,2): "Rama Navami"})
custom_holidays.append({"{0}-{1}-{2}".format(year,4,6): "Mahavir Jayanti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,4,9): "First day of Passover"})
custom_holidays.append({"{0}-{1}-{2}".format(year,4,9): "Maundy Thursday"})
custom_holidays.append({"{0}-{1}-{2}".format(year,4,10): "Good Friday"})
custom_holidays.append({"{0}-{1}-{2}".format(year,4,12): "Easter Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,4,13): "Vaisakhi"})
custom_holidays.append({"{0}-{1}-{2}".format(year,4,14): "Mesadi/Vaisakhadi"})
custom_holidays.append({"{0}-{1}-{2}".format(year,4,14): "Ambedkar Jayanti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,5,1): "Maharashtra Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,5,7): "Buddha Purnima/Vesak"})
custom_holidays.append({"{0}-{1}-{2}".format(year,5,10): "Mother's Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,5,22): "Jamat Ul-Vida"})
custom_holidays.append({"{0}-{1}-{2}".format(year,5,25): "Ramzan Id/Eid-ul-Fitar"})
custom_holidays.append({"{0}-{1}-{2}".format(year,6,21): "Father's Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,6,23): "Rath Yatra"})
custom_holidays.append({"{0}-{1}-{2}".format(year,7,5): "Guru Purnima"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,1): "Bakr Id/Eid ul-Adha"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,2): "Friendship Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,3): "Raksha Bandhan (Rakhi)"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,11): "Janmashtami (Smarta)"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,12): "Janmashtami"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,15): "Independence Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,16): "Parsi New Year"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,22): "Ganesh Chaturthi/Vinayaka Chaturthi"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,30): "Muharram/Ashura"})
custom_holidays.append({"{0}-{1}-{2}".format(year,8,31): "Onam"})
custom_holidays.append({"{0}-{1}-{2}".format(year,9,22): "September Equinox"})
custom_holidays.append({"{0}-{1}-{2}".format(year,10,2): "Mahatma Gandhi Jayanti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,10,22): "Maha Saptami"})
custom_holidays.append({"{0}-{1}-{2}".format(year,10,23): "Maha Ashtami"})
custom_holidays.append({"{0}-{1}-{2}".format(year,10,24): "Maha Navami"})
custom_holidays.append({"{0}-{1}-{2}".format(year,10,25): "Dussehra"})
custom_holidays.append({"{0}-{1}-{2}".format(year,10,30): "Milad un-Nabi/Id-e-Milad"})
custom_holidays.append({"{0}-{1}-{2}".format(year,10,31): "Halloween"})
custom_holidays.append({"{0}-{1}-{2}".format(year,10,31): "Maharishi Valmiki Jayanti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,11,4): "Karaka Chaturthi (Karva Chauth)"})
custom_holidays.append({"{0}-{1}-{2}".format(year,11,14): "Naraka Chaturdasi"})
custom_holidays.append({"{0}-{1}-{2}".format(year,11,14): "Diwali/Deepavali"})
custom_holidays.append({"{0}-{1}-{2}".format(year,11,15): "Govardhan Puja"})
custom_holidays.append({"{0}-{1}-{2}".format(year,11,16): "Bhai Duj"})
custom_holidays.append({"{0}-{1}-{2}".format(year,11,20): "Chhat Puja"})
custom_holidays.append({"{0}-{1}-{2}".format(year,11,24): "Guru Tegh Bahadur's Martyrdom Day"})
custom_holidays.append({"{0}-{1}-{2}".format(year,11,30): "Guru Nanak Jayanti"})
custom_holidays.append({"{0}-{1}-{2}".format(year,12,11): "First Day of Hanukkah"})
custom_holidays.append({"{0}-{1}-{2}".format(year,12,18): "Last day of Hanukkah"})
custom_holidays.append({"{0}-{1}-{2}".format(year,12,21): "December Solstice"})
custom_holidays.append({"{0}-{1}-{2}".format(year,12,24): "Christmas Eve"})
custom_holidays.append({"{0}-{1}-{2}".format(year,12,25): "Christmas"})
custom_holidays.append({"{0}-{1}-{2}".format(year,12,31): "New Year's Eve"})





